disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

line_length:
  warning: 300
  error: 800
